#!/bin/bash

#A bash script for downloading videos from YouTube, ripping the audio and fixing to audio to make
#it consistent in volume. The script then places the resulting .ogg files into other directories
#from which I happen to use BitTorrent Sync to share among my devices for listening at my convenience.

#This script also make use of youtube-dl, avconv, and sox.

cd ~/videos/youtube/
mkdir "$2"
cd "$2"

# Video file name
V=$(youtube-dl --get-filename $1)

# Download video
youtube-dl "$1"

echo "Ripping audio..."

avconv -i "$V" "$2".flac

echo "Converting to mono..."

sox -V2 "$2".flac -c 1 "$2".mono.flac

echo "Running highpass filter..."

sox -V2 "$2".mono.flac "$2".mono.hp.flac highpass 80

echo "Running dynamic compression..."

sox -V2 "$2".mono.hp.flac "$2".mono.hp.comp.flac compand 0.3,1.5 6:-60,-45,-15 -7 -90 0.3

echo "Normalizing..."

sox -V2 "$2".mono.hp.comp.flac "$2".mono.hp.comp.norm.flac gain -n -1

echo "Converting to Ogg Vorbis..."

sox -V2 "$2".mono.hp.comp.norm.flac "$2".ogg

cd ..

cp -v "$2"/*.ogg ./Listen

cp -v "$2"/*.ogg ./Share

rm -rv "$2"
