#!/bin/bash

cd ~/videos/youtube/
mkdir "$2"
cd "$2"

# Video file name
V=$(youtube-dl --get-filename $1)

# Download video
youtube-dl "$1"

avconv -i "$V" "$2".flac
echo "#########################"
echo "## Video to Audio Done ##"
echo "#########################"

sox -V2 "$2".flac -c 1 "$2".mono.flac
echo "#########################"
echo "## Stereo to Mono Done ##"
echo "#########################"

sox -V2 "$2".mono.flac "$2".mono.hp.flac highpass 80
echo "###################"
echo "## Highpass Done ##"
echo "###################"

sox -V2 "$2".mono.hp.flac "$2".mono.hp.comp.flac compand 0.3,1.5 6:-60,-45,-15 -7 -90 0.3
echo "######################"
echo "## Compression Done ##"
echo "######################"

sox -V2 "$2".mono.hp.comp.flac "$2".mono.hp.comp.norm.flac gain -n -1
echo "########################"
echo "## Normalization Done ##"
echo "########################"

sox -V2 "$2".mono.hp.comp.norm.flac "$2".ogg
echo "############################"
echo "## Conversion to ogg Done ##"
echo "############################"

cd ..

cp -v "$2"/*.ogg ./Listen

cp -v "$2"/*.ogg ./Share

rm -rv "$2"
